# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-web-content
spec:
  template:
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo '<h1>Hello from Minikube!</h1>' > /mnt/data/index.html"]
        volumeMounts:
        - name: web-content
          mountPath: /mnt/data
      restartPolicy: Never
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc

